# SPDX-FileCopyrightText: 2020 Benedict Harcourt
#
# SPDX-License-Identifier: BSD-2-Clause

name: JS Lint

on:
  push:
    branches:
      - mainline
  pull_request:

jobs:
  es-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ESLint
        run: npx eslint . --ext .js --ignore-pattern ./node_modules
